# Generated by Django 3.0.5 on 2020-04-16 03:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_details', ckeditor.fields.RichTextField()),
                ('start', models.DateTimeField(blank=True, db_index=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, db_index=True, verbose_name='end')),
                ('course_time', models.TimeField(blank=True)),
                ('course_price', models.IntegerField(blank=True)),
                ('course_photo', models.ImageField(blank=True, default='secretary/courses/default.png', null=True, upload_to='courses/')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
