# Generated by Django 3.0.5 on 2020-04-16 17:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_details', ckeditor.fields.RichTextField()),
                ('start', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('course_time', models.TimeField(blank=True, null=True)),
                ('course_price', models.IntegerField(blank=True, null=True)),
                ('course_photo', models.ImageField(blank=True, default='secretary/courses/default.png', null=True, upload_to='courses/')),
            ],
        ),
    ]
