# Generated by Django 3.0.5 on 2020-04-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secretary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.DateTimeField(blank=True, verbose_name='end'),
        ),
    ]
