# Generated by Django 3.0.5 on 2020-04-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secretary', '0002_auto_20200416_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
