# Generated by Django 3.0.5 on 2020-04-15 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0004_auto_20200415_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='person',
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='person'),
        ),
    ]
