# Generated by Django 3.0.5 on 2020-04-15 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0005_auto_20200415_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='person',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='person'),
        ),
    ]
