# Generated by Django 3.0.5 on 2020-04-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='gender',
            field=models.IntegerField(choices=[('male', 'male'), ('female', 'female'), ('not specified', 'not specified')], default=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[('male', 'male'), ('female', 'female'), ('not specified', 'not specified')], default=2),
        ),
    ]
